export interface CustomerInfo {
  id: string | undefined;
  gender: string | undefined;
  title: string | undefined;
  first: string | undefined;
  last: string | undefined;
  email: string | undefined;
  phone: string | undefined;
  cell: string | undefined;
  login: string | undefined;
  password: string | undefined;
  address1: string | undefined;
  address2: string | undefined;
  state: string | undefined;
  country: string | undefined;
  dob: string | undefined;
  age: string | undefined;
  since: string | undefined;
  registered: string | undefined;
  picture: string | undefined;
  thumbnail: string | undefined;
  uuid: string | undefined;
}
